### PR TITLE
TS transformers

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
I rewrote the various touch-ups using TypeScript transformers 'before' and 'after'. Since it now works from the complier AST, it should provide better/safer handling then raw string/regex (i.e. multiline statements, multiple statements on a single line)

One issue with current implementation: comment "attached" to removed statement are also removed. It in not yet clear how it can be worked around.

### CODE REVIEW

**Comment by grant** [comment]
Thanks! Looks good from a high level.
Close #5 if this PR fixes that.
Let me know if you want me to publish.

**Comment by PopGoesTheWza** [comment]
I added first line comment with the gas and ts version. You may remove it if you prefer

**Comment by grant** [comment]
That's fine.
Maybe update the README to show an example of what the function actually outputs now?

**Comment by PopGoesTheWza** [comment]
Publishing ts2gas might require clasp to also be updated/bump in order to benefit from latest TS version

**Comment by PopGoesTheWza** [comment]
working on the transformers was interesting. Too bad documentation is lacking

**Comment by grant** [comment]
Published with `ts2gas@1.5`.

**Pull request merged**
