### PR TITLE
3.5.0 rc

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
addresses #46

### CODE REVIEW

**Comment by PopGoesTheWza** [comment]
@grant do you wish to review/comment?

**Comment by grant** [comment]
> @grant do you wish to review/comment?

No, but you can get a different reviewer like @shinout or other active members.

**Comment by PopGoesTheWza** [comment]
@shinout do you wish to review/comment?

**Comment by shinout** [comment]
@PopGoesTheWza Yes.

**Comment by PopGoesTheWza** [comment]
@grant can you please issue a new npm release?

**Comment by shinout** [comment]
@grant can you allow me to join here as a collaborator?

**Comment by grant** [comment]
- Can you give me your npm username @PopGoesTheWza so I can grant you access?
- Granted @shinout access.

**Comment by PopGoesTheWza** [comment]
@grant my npm username is `popgoesthewza`

**Comment by grant** [comment]
Granted to `popgoesthewza`.

**Pull request merged**
